Change: the retry logic

diff --git a/.github/workflows/macos_x86_64.yml b/.github/workflows/macos_x86_64.yml
--- a/.github/workflows/macos_x86_64.yml
+++ b/.github/workflows/macos_x86_64.yml
@@ -42,6 +42,7 @@ jobs:
       run: cmake --build build --config Release
 
     - name: Test with Retry
+      working-directory: build
       run: |
         max_retries=10
         attempt=1
@@ -50,14 +51,12 @@ jobs:
           ctest --output-on-failure -C Release
           if [ $? -eq 0 ]; then
             echo "Tests passed on attempt $attempt"
-            break
+            exit 0
           else
             echo "Tests failed on attempt $attempt"
           fi
           attempt=$((attempt + 1))
+          sleep 1
         done
-        if [ $attempt -gt $max_retries ]; then
-          echo "All $max_retries attempts failed"
-          exit 1
-        fi
-      working-directory: build
+        echo "All $max_retries attempts failed"
+        exit 1
diff --git a/.github/workflows/windows_x86_64.yml b/.github/workflows/windows_x86_64.yml
--- a/.github/workflows/windows_x86_64.yml
+++ b/.github/workflows/windows_x86_64.yml
@@ -78,6 +78,7 @@ jobs:
         ls -R build/lib/
 
     - name: Test with Retry
+      working-directory: build
       run: |
         max_retries=10
         attempt=1
@@ -86,17 +87,15 @@ jobs:
           ctest --output-on-failure -C ${{ env.BUILD_TYPE }}
           if [ $? -eq 0 ]; then
             echo "Tests passed on attempt $attempt"
-            break
+            exit 0
           else
             echo "Tests failed on attempt $attempt"
           fi
           attempt=$((attempt + 1))
+          sleep 1
         done
-        if [ $attempt -gt $max_retries ]; then
-          echo "All $max_retries attempts failed"
-          exit 1
-        fi
-      working-directory: build
+        echo "All $max_retries attempts failed"
+        exit 1
 
     - name: Diagnostics if build fails
       if: failure()
