Fix: ubuntu by install cmake directly

diff --git a/.github/workflows/ubuntu_X86_64.yml b/.github/workflows/ubuntu_X86_64.yml
--- a/.github/workflows/ubuntu_X86_64.yml
+++ b/.github/workflows/ubuntu_X86_64.yml
@@ -16,10 +16,13 @@ jobs:
       uses: actions/checkout@v4
 
     - name: Install dependencies
-      run: sudo apt-get update && sudo apt-get install -y libgtest-dev libtbb-dev cmake
+      run: |
+        sudo apt-get update; sudo apt-get install -y libgtest-dev libtbb-dev cmake ninja-build
 
-    - name: Setup CMake and Ninja
-      uses: lukka/get-cmake@v3.21.1
+    # - name: Setup CMake and Ninja
+    #   uses: lukka/get-cmake@v3.21.1
+    #   with:
+    #     cache: false
 
     - name: Check GCC Version
       run: g++ --version
@@ -28,7 +31,9 @@ jobs:
       run: mkdir build
 
     - name: Configure CMake
-      run: cmake -S . -B build -DBUILD_CIRCULARBUFFER_MULTI_THREADING=ON -DCMAKE_BUILD_TYPE=Release
+      run: cmake -S . -B build -G Ninja \
+          -DBUILD_CIRCULARBUFFER_MULTI_THREADING=ON \
+          -DCMAKE_BUILD_TYPE=Release
 
     - name: Build
       run: cmake --build build --config Release
@@ -36,19 +41,17 @@ jobs:
     - name: Test with Retry
       working-directory: build
       run: |
-        set +e  # Disable exit on error
+        set +e  # disable immediate exit
         max_retries=10
         attempt=1
         while [ $attempt -le $max_retries ]; do
           echo "Test attempt $attempt"
           ctest --output-on-failure -C Release
-          test_result=$?
-          if [ $test_result -eq 0 ]; then
+          if [ $? -eq 0 ]; then
             echo "Tests passed on attempt $attempt"
             exit 0
-          else
-            echo "Tests failed on attempt $attempt"
           fi
+          echo "Tests failed on attempt $attempt"
           attempt=$((attempt + 1))
           sleep 1
         done
